version: '3'
services:
  accounts:
    image: ezbank/accounts:latest
    ports:
      - '8080:8080'
    deploy:
      resources:
        limits:
          memory: 700m
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ezbank-compose-network
  cards:
    image: ezbank/cards:latest
    ports:
      - '9090:9090'
    deploy:
      resources:
        limits:
          memory: 700m
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ezbank-compose-network
  loans:
    image: ezbank/loans:latest
    ports:
      - '8090:8090'
    deploy:
      resources:
        limits:
          memory: 700m
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ezbank-compose-network
  configServer:
    image: ezbank/configs:latest
    ports:
      - '8071:8071'
    deploy:
      resources:
        limits:
          memory: 700m
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ezbank-compose-network
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'
    deploy:
      resources:
        limits:
          memory: 700m
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ezbank-compose-network
networks:
  ezbank-compose-network:
    driver: bridge
