server:
  port: 8090
spring:
  application:
    name: Loans
  datasource:
    url: jdbc:h2:file:/Users/eliezeroliveira/data/loandb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
