spring:
  application:
    name: "apigateway"
  config:
    import: "optional:configserver:http://localhost:8085/"
  cloud:
    gateway:
      httpclient:
        response-timeout: 5s
        connect-timeout: 3000
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 10s # This is bigger than HTTP timeout just to simulate without follow into the circuitbreaker fallback

  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s