logging:
  level:
    root: INFO
  file:
    name: logs/accounts-dev.log
spring:
  datasource:
    url: jdbc:h2:file:/mnt/data/accountdb;AUTO_SERVER=TRUE
  config:
    activate:
      on-profile: "prod"