services:
  network-deploy-service:
    networks:
      - ezbank-compose-network
    extra_hosts:
      - host.docker.internal:host-gateway

  microservice-base-config:
    extends:
        service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_CONFIG_URI: 'configserver:http://configserver:8085'
      SPRING_PROFILES_ACTIVE: 'default'
    depends_on:
      configserver:
        condition: service_healthy

  microservice-eureka-config:
    extends:
      service: microservice-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8081/eureka/