services:
  network-config:
    networks:
      - ezbank-vlan

  base-config:
    extends:
      service: network-config
    deploy:
      resources:
        limits:
          memory: 700m

  eureka-config:
    extends:
      service: base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      SPRING_BOOT_APPLICATION_LOG_LEVEL: DEBUG

  services-config:
    extends:
      service: eureka-config
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8081/eureka/

