services:
  configserver:
    image: "ezbank/configserver:latest"
    container_name: configserver-ms
    networks:
      - eznetwork
    ports:
      - "8085:8085"
    healthcheck:
      test: "curl --fail --silent configserver:8085/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  eurekaserver:
    image: "ezbank/eurekaserver:latest"
    container_name: eurekaserver-ms
    networks:
      - eznetwork
    ports:
      - "8081:8081"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085/
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: "ezbank/accounts:latest"
    container_name: accounts-ms
    networks:
      - eznetwork
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent accounts:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085/
      SPRING_BOOT_APPLICATION_LOG_LEVEL: DEBUG
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8081/eureka/

  cards:
    image: "ezbank/cards:latest"
    container_name: cards-ms
    networks:
      - eznetwork
    ports:
      - "8091:8091"
    healthcheck:
      test: "curl --fail --silent cards:8091/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085/
      SPRING_BOOT_APPLICATION_LOG_LEVEL: DEBUG
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8081/eureka/

  loans:
    image: "ezbank/loans:latest"
    container_name: loans-ms
    networks:
      - eznetwork
    ports:
      - "8092:8092"
    healthcheck:
      test: "curl --fail --silent loans:8092/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085/
      SPRING_BOOT_APPLICATION_LOG_LEVEL: DEBUG
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8081/eureka/

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - eznetwork
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight-ms
    networks:
      - eznetwork
    ports:
      - "8083:5540"
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      - redis
    restart: always

  apigateway:
    image: "ezbank/apigateway:latest"
    container_name: apigateway-ms
    networks:
      - eznetwork
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent apigateway:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085/
      SPRING_BOOT_APPLICATION_LOG_LEVEL: DEBUG
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8081/eureka/


networks:
  eznetwork:
    driver: bridge

#  rabbitmq:
#    image: rabbitmq:latest
#    hostname: rabbitmq
#    ports:
#      - '5672:5672'
#      - '15672:15672'
#    command: ["rabbitmq-plugins", "enable", "rabbitmq_management"]
#    healthcheck:
#      test: ["CMD", "rabbitmqctl", "status"]
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    extends:
#      file: common-config.yml
#      service: network-deploy-service

