services:
#  rabbitmq:
#    image: rabbitmq:latest
#    hostname: rabbitmq
#    ports:
#      - '5672:5672'
#      - '15672:15672'
#    command: ["rabbitmq-plugins", "enable", "rabbitmq_management"]
#    healthcheck:
#      test: ["CMD", "rabbitmqctl", "status"]
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    extends:
#      file: common-config.yml
#      service: network-deploy-service

  configserver:
    image: ezbank/configserver:latest
    container_name: configserver-ms
    ports:
      - '8085:8085'
    healthcheck:
      test: "curl --fail --silent localhost:8085/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: base-config

  eurekaserver:
    image: "ezbank/eurekaserver:latest"
    container_name: eurekaserver-ms
    ports:
      - "8081:8081"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: eureka-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: ezbank/accounts:latest
    container_name: accounts-ms
    ports:
      - '8090:8090'
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: services-config

  cards:
    image: ezbank/cards:latest
    container_name: cards-ms
    ports:
      - '8091:8091'
    healthcheck:
      test: "curl --fail --silent localhost:8091/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: services-config

  loans:
    image: ezbank/loans:latest
    container_name: loans-ms
    ports:
      - '8092:8092'
    healthcheck:
      test: "curl --fail --silent localhost:8092/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: services-config

  apigateway:
    image: ezbank/apigateway:latest
    container_name: apigateway-ms
    ports:
      - "8080:8080"
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: eureka-config

networks:
  ezbank-vlan:
    driver: bridge
