services:
#  rabbitmq:
#    image: rabbitmq:latest
#    hostname: rabbitmq
#    ports:
#      - '5672:5672'
#      - '15672:15672'
#    command: ["rabbitmq-plugins", "enable", "rabbitmq_management"]
#    healthcheck:
#      test: ["CMD", "rabbitmqctl", "status"]
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    extends:
#      file: common-config.yml
#      service: network-deploy-service

  eurekaserver:
    image: ezbank/eurekaserver:latest
    ports:
      - "8081:8081"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  configserver:
    image: ezbank/configserver:latest
    ports:
      - '8085:8085'
    healthcheck:
      test: "curl --fail --silent localhost:8085/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      rabbitmq:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: ezbank/accounts:latest
    ports:
      - '8090:8090'
    extends:
      file: common-config.yml
      service: microservice-config

  cards:
    image: ezbank/cards:latest
    ports:
      - '8091:8091'
    extends:
      file: common-config.yml
      service: microservice-config

  loans:
    image: ezbank/loans:latest
    ports:
      - '8092:8092'
    extends:
      file: common-config.yml
      service: microservice-config

networks:
  ezbank-compose-network:
    driver: bridge
