discovery.docker "docker_log_files" {
  host             = "unix:///var/run/docker.sock"
  refresh_interval = "5s"
}

discovery.relabel "docker_log_files" {
  targets = []
  
  rule {
  source_labels = ["__meta_docker_container_name"]
  regex         = "/(.*)"
  target_label  = "container"
  }
}

loki.source.docker "docker_log_files" {
  host             = "unix:///var/run/docker.sock"
  targets          = discovery.docker.docker_log_files.targets
  forward_to       = [loki.write.default.receiver]
  relabel_rules    = discovery.relabel.docker_log_files.rules
  refresh_interval = "5s"
}

loki.write "default" {
  endpoint {
    url       = "http://loki:3100/loki/api/v1/push"
    tenant_id = "EzBank"
  }
}